# Copyright (c) 2026 Cisco Systems, Inc. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

[program:dshell_client]
command=/opt/cisco/syncd/bin/dshell_client.py
priority=6
autostart=true
autorestart=true
startsecs=0
stdout_logfile=syslog
stderr_logfile=syslog

[program:puntpkthandler]
environment=GOTRACEBACK="system"
command=/opt/cisco/syncd/bin/puntpkthandler
priority=6
autostart=false
autorestart=true
startsecs=0
stdout_logfile=syslog
stderr_logfile=syslog
dependent_startup=true
dependent_startup_wait_for=syncd:running
