#
# SPDX-FileCopyrightText: NVIDIA CORPORATION & AFFILIATES
# Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

# DOCA Installer is distributed as an architecture-specific Debian package.
DOCA_INSTALLER_VERSION = 2.0.3
DOCA_INSTALLER = doca-installer_$(DOCA_INSTALLER_VERSION)_$(CONFIGURED_ARCH).deb

DOCA_INSTALLER_ASSETS_GITHUB_URL = https://github.com/Mellanox/sonic-bluefield-packages
DOCA_INSTALLER_ASSETS_RELEASE_TAG = doca-installer-$(DOCA_INSTALLER_VERSION)-$(BLDENV)-$(CONFIGURED_ARCH)
DOCA_INSTALLER_ASSETS_URL = $(DOCA_INSTALLER_ASSETS_GITHUB_URL)/releases/download/$(DOCA_INSTALLER_ASSETS_RELEASE_TAG)
$(DOCA_INSTALLER)_URL = $(DOCA_INSTALLER_ASSETS_URL)/$(DOCA_INSTALLER)

SONIC_ONLINE_DEBS += $(DOCA_INSTALLER)

export DOCA_INSTALLER DOCA_INSTALLER_VERSION
