# name          lanes             alias             index       speed          mtu
Ethernet1               1         etp1                1          1000          1500
Ethernet2               2         etp2                2          1000          1500
Ethernet3               3         etp3                3          1000          1500
