CONSOLE_SPEED=9600
ONIE_PLATFORM_EXTRA_CMDLINE_LINUX="processor.max_cstate=0 intel_idle.max_cstate=0 intel_pstate=disable idle=poll modprobe.blacklist=amd_xgbe,i2c_piix4,ixgbe,r8168,r8169,igb,fpga_pcie_drv,i2c_i801,wb_i2c_i801,pgdrv,i2c_asf,snd_hda_intel,asix,amd_pmf,amd_sfh"
ONIE_IMAGE_PART_SIZE=1048576
