# Copyright (c) 2026 Cisco Systems, Inc. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

[module]
repo=git@github.com:Cisco-8000-sonic/platform-cisco-8000.git
ref=0.cisco.master.1.0.0
path=platform/cisco/src
