# Docker base image (based on Debian Trixie)

DOCKER_BASE_TRIXIE = docker-base-trixie.gz
$(DOCKER_BASE_TRIXIE)_PATH = $(DOCKERS_PATH)/docker-base-trixie

$(DOCKER_BASE_TRIXIE)_DEPENDS += $(SOCAT)
$(DOCKER_BASE_TRIXIE)_DEPENDS += $(IPROUTE2)
$(DOCKER_BASE_TRIXIE)_DEPENDS += $(RSYSLOG) $(RSYSLOG_RELP)

GDB = gdb
GDBSERVER = gdbserver
VIM = vim
OPENSSH = openssh-client
SSHPASS = sshpass
STRACE = strace

ifeq ($(INCLUDE_FIPS), y)
$(DOCKER_BASE_TRIXIE)_DEPENDS += $(FIPS_OPENSSL_LIBSSL) $(FIPS_OPENSSL_LIBSSL_DEV) $(FIPS_OPENSSL) $(SYMCRYPT_OPENSSL) \
    $(FIPS_KRB5) $(FIPS_KRB5_SUPPORT0) $(FIPS_KRB5_3) $(FIPS_KRB5_LIBGSSAPI)
endif

$(DOCKER_BASE_TRIXIE)_DBG_IMAGE_PACKAGES += $(GDB) $(GDBSERVER) $(VIM) $(SSHPASS) $(STRACE)

ifeq ($(INCLUDE_FIPS), y)
$(DOCKER_BASE_TRIXIE)_DBG_DEPENDS += $(FIPS_OPENSSH_CLIENT)
else
$(DOCKER_BASE_TRIXIE)_DBG_IMAGE_PACKAGES += $(OPENSSH)
endif

SONIC_DOCKER_IMAGES += $(DOCKER_BASE_TRIXIE)
SONIC_TRIXIE_DOCKERS += $(DOCKER_BASE_TRIXIE)
