# docker image for smart-switch/DASH high availability services

DOCKER_HA_STEM = docker-ha
DOCKER_HA = $(DOCKER_HA_STEM).gz
DOCKER_HA_DBG = $(DOCKER_HA_STEM)-$(DBG_IMAGE_MARK).gz

$(DOCKER_HA)_PATH = $(DOCKERS_PATH)/$(DOCKER_HA_STEM)

$(DOCKER_HA)_DEPENDS += $(DASH_HA)
$(DOCKER_HA)_DBG_DEPENDS = $($(DOCKER_SWSS_LAYER_BOOKWORM)_DBG_DEPENDS)
$(DOCKER_HA)_DBG_DEPENDS += $(DASH_HA_DBG)

$(DOCKER_HA)_DBG_IMAGE_PACKAGES = $($(DOCKER_SWSS_LAYER_BOOKWORM)_DBG_IMAGE_PACKAGES)

$(DOCKER_HA)_LOAD_DOCKERS += $(DOCKER_SWSS_LAYER_BOOKWORM)

$(DOCKER_HA)_VERSION = 1.0.0
$(DOCKER_HA)_PACKAGE_NAME = ha
$(DOCKER_HA)_WARM_SHUTDOWN_BEFORE = syncd
$(DOCKER_HA)_WARM_SHUTDOWN_AFTER = swss
$(DOCKER_HA)_FAST_SHUTDOWN_BEFORE = syncd
$(DOCKER_HA)_FAST_SHUTDOWN_AFTER = swss

SONIC_DOCKER_IMAGES += $(DOCKER_HA)
ifeq ($(INCLUDE_HA), y)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_HA)
endif

SONIC_DOCKER_DBG_IMAGES += $(DOCKER_HA_DBG)
ifeq ($(INCLUDE_HA), y)
SONIC_INSTALL_DOCKER_DBG_IMAGES += $(DOCKER_HA_DBG)
endif

$(DOCKER_HA)_CONTAINER_NAME = ha
$(DOCKER_HA)_RUN_OPT += -t
$(DOCKER_HA)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro
$(DOCKER_HA)_RUN_OPT += -v /etc/timezone:/etc/timezone:ro 

SONIC_BOOKWORM_DOCKERS += $(DOCKER_HA)
SONIC_BOOKWORM_DBG_DOCKERS += $(DOCKER_HA_DBG)
