RSYSLOG_VERSION = 8.2504.0
RSYSLOG_VERSION_SUFFIX = 1+deb13u2
RSYSLOG_VERSION_FULL = $(RSYSLOG_VERSION)-$(RSYSLOG_VERSION_SUFFIX)

RSYSLOG = rsyslog_$(RSYSLOG_VERSION_FULL)_$(CONFIGURED_ARCH).deb
$(RSYSLOG)_SRC_PATH = $(SRC_PATH)/rsyslogd
SONIC_MAKE_DEBS += $(RSYSLOG)

RSYSLOG_DBG = rsyslog-dbgsym_$(RSYSLOG_VERSION_FULL)_$(CONFIGURED_ARCH).deb
$(RSYSLOG_DBG)_DEPENDS += $(RSYSLOG)
$(RSYSLOG_DBG)_RDEPENDS += $(RSYSLOG)
$(eval $(call add_derived_package,$(RSYSLOG),$(RSYSLOG_DBG)))

RSYSLOG_RELP = rsyslog-relp_$(RSYSLOG_VERSION_FULL)_$(CONFIGURED_ARCH).deb
$(eval $(call add_derived_package,$(RSYSLOG),$(RSYSLOG_RELP)))

RSYSLOG_RELP_DBG = rsyslog-relp-dbgsym_$(RSYSLOG_VERSION_FULL)_$(CONFIGURED_ARCH).deb
$(RSYSLOG_RELP_DBG)_DEPENDS += $(RSYSLOG_RELP)
$(RSYSLOG_RELP_DBG)_RDEPENDS += $(RSYSLOG_RELP)
$(eval $(call add_derived_package,$(RSYSLOG),$(RSYSLOG_RELP_DBG)))

# Export these variables so they can be used in a sub-make
export RSYSLOG_VERSION
export RSYSLOG_VERSION_FULL
export RSYSLOG
